/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_gerardodiaz;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gerar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_Sign = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jb_Artista = new javax.swing.JButton();
        jb_Cliente = new javax.swing.JButton();
        jd_signC = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_usuarioC = new javax.swing.JTextField();
        pf_contraC = new javax.swing.JPasswordField();
        jb_GuardarC = new javax.swing.JButton();
        tt_edadC = new javax.swing.JTextField();
        jd_signA = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_usuarioA = new javax.swing.JTextField();
        pf_contraA = new javax.swing.JPasswordField();
        tt_edadA = new javax.swing.JTextField();
        jb_GuardarA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreA = new javax.swing.JTextField();
        jd_login = new javax.swing.JDialog();
        jb_spotify1 = new javax.swing.JLabel();
        jf_Login = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jb_Cliente1 = new javax.swing.JButton();
        jb_Artista1 = new javax.swing.JButton();
        jd_LoginC = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_usuarioC1 = new javax.swing.JTextField();
        pf_contraC1 = new javax.swing.JPasswordField();
        jb_GuardarC1 = new javax.swing.JButton();
        jd_LoginA = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_usuarioA1 = new javax.swing.JTextField();
        pf_contraA1 = new javax.swing.JPasswordField();
        jb_GuardarA1 = new javax.swing.JButton();
        jf_Artistas = new javax.swing.JFrame();
        CRUD = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_1 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_ListarU = new javax.swing.JMenuItem();
        jm_ModificarU = new javax.swing.JMenuItem();
        jm_DeleteU = new javax.swing.JMenuItem();
        jm_ListarA = new javax.swing.JMenuItem();
        jm_ModificarA = new javax.swing.JMenuItem();
        jm_DeleteA = new javax.swing.JMenuItem();
        jb_spotify = new javax.swing.JLabel();
        jb_pic = new javax.swing.JLabel();
        jb_Sign = new javax.swing.JButton();
        jb_Login = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        jf_Sign.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Spotify");

        jb_Artista.setBackground(new java.awt.Color(0, 0, 0));
        jb_Artista.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jb_Artista.setForeground(new java.awt.Color(102, 255, 51));
        jb_Artista.setText("Artista");
        jb_Artista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ArtistaMouseClicked(evt);
            }
        });

        jb_Cliente.setBackground(new java.awt.Color(0, 0, 0));
        jb_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jb_Cliente.setForeground(new java.awt.Color(102, 255, 0));
        jb_Cliente.setText("Cliente");
        jb_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_SignLayout = new javax.swing.GroupLayout(jf_Sign.getContentPane());
        jf_Sign.getContentPane().setLayout(jf_SignLayout);
        jf_SignLayout.setHorizontalGroup(
            jf_SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_SignLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_SignLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jf_SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jf_SignLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );
        jf_SignLayout.setVerticalGroup(
            jf_SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_SignLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jb_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jf_SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_SignLayout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(jb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Spotify");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contrasenia");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edad");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuario");

        tf_usuarioC.setBackground(new java.awt.Color(0, 0, 0));
        tf_usuarioC.setForeground(new java.awt.Color(102, 255, 51));

        pf_contraC.setBackground(new java.awt.Color(0, 0, 0));
        pf_contraC.setForeground(new java.awt.Color(102, 255, 0));

        jb_GuardarC.setBackground(new java.awt.Color(0, 0, 0));
        jb_GuardarC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_GuardarC.setForeground(new java.awt.Color(102, 255, 51));
        jb_GuardarC.setText("Guardar");
        jb_GuardarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarCMouseClicked(evt);
            }
        });

        tt_edadC.setBackground(new java.awt.Color(0, 0, 0));
        tt_edadC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tt_edadC.setForeground(new java.awt.Color(153, 255, 51));
        tt_edadC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jd_signCLayout = new javax.swing.GroupLayout(jd_signC.getContentPane());
        jd_signC.getContentPane().setLayout(jd_signCLayout);
        jd_signCLayout.setHorizontalGroup(
            jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signCLayout.createSequentialGroup()
                .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signCLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_signCLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_GuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_signCLayout.createSequentialGroup()
                                .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_usuarioC)
                                    .addComponent(pf_contraC)
                                    .addComponent(tt_edadC, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jd_signCLayout.setVerticalGroup(
            jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signCLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuarioC)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pf_contraC, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jd_signCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt_edadC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_GuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Spotify");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Usuario");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Contrasenia");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Edad");

        tf_usuarioA.setBackground(new java.awt.Color(0, 0, 0));
        tf_usuarioA.setForeground(new java.awt.Color(102, 255, 51));
        tf_usuarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioAActionPerformed(evt);
            }
        });

        pf_contraA.setBackground(new java.awt.Color(0, 0, 0));
        pf_contraA.setForeground(new java.awt.Color(102, 255, 0));

        tt_edadA.setBackground(new java.awt.Color(0, 0, 0));
        tt_edadA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tt_edadA.setForeground(new java.awt.Color(153, 255, 51));
        tt_edadA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jb_GuardarA.setBackground(new java.awt.Color(0, 0, 0));
        jb_GuardarA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_GuardarA.setForeground(new java.awt.Color(102, 255, 51));
        jb_GuardarA.setText("Guardar");
        jb_GuardarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarAMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nombre Artistico");

        tf_nombreA.setBackground(new java.awt.Color(0, 0, 0));
        tf_nombreA.setForeground(new java.awt.Color(102, 255, 51));
        tf_nombreA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_signALayout = new javax.swing.GroupLayout(jd_signA.getContentPane());
        jd_signA.getContentPane().setLayout(jd_signALayout);
        jd_signALayout.setHorizontalGroup(
            jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signALayout.createSequentialGroup()
                .addGroup(jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signALayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_signALayout.createSequentialGroup()
                        .addGroup(jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_signALayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_signALayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signALayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pf_contraA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tt_edadA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_usuarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_signALayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jb_GuardarA, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jd_signALayout.setVerticalGroup(
            jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signALayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuarioA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_contraA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jd_signALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt_edadA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jb_GuardarA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jb_spotify1.setBackground(new java.awt.Color(0, 0, 0));
        jb_spotify1.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jb_spotify1.setForeground(new java.awt.Color(51, 255, 0));
        jb_spotify1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jb_spotify1.setText("Spotify");

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jb_spotify1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_spotify1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Spotify");

        jb_Cliente1.setBackground(new java.awt.Color(0, 0, 0));
        jb_Cliente1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jb_Cliente1.setForeground(new java.awt.Color(102, 255, 0));
        jb_Cliente1.setText("Cliente");
        jb_Cliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Cliente1MouseClicked(evt);
            }
        });

        jb_Artista1.setBackground(new java.awt.Color(0, 0, 0));
        jb_Artista1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jb_Artista1.setForeground(new java.awt.Color(102, 255, 51));
        jb_Artista1.setText("Artista");
        jb_Artista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Artista1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_LoginLayout = new javax.swing.GroupLayout(jf_Login.getContentPane());
        jf_Login.getContentPane().setLayout(jf_LoginLayout);
        jf_LoginLayout.setHorizontalGroup(
            jf_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(jf_LoginLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jb_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jf_LoginLayout.setVerticalGroup(
            jf_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jf_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Spotify");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Usuario");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 255, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Contrasenia");

        tf_usuarioC1.setBackground(new java.awt.Color(0, 0, 0));
        tf_usuarioC1.setForeground(new java.awt.Color(102, 255, 51));

        pf_contraC1.setBackground(new java.awt.Color(0, 0, 0));
        pf_contraC1.setForeground(new java.awt.Color(102, 255, 0));

        jb_GuardarC1.setBackground(new java.awt.Color(0, 0, 0));
        jb_GuardarC1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_GuardarC1.setForeground(new java.awt.Color(102, 255, 51));
        jb_GuardarC1.setText("LOGIN");
        jb_GuardarC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarC1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginCLayout = new javax.swing.GroupLayout(jd_LoginC.getContentPane());
        jd_LoginC.getContentPane().setLayout(jd_LoginCLayout);
        jd_LoginCLayout.setHorizontalGroup(
            jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginCLayout.createSequentialGroup()
                .addGroup(jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LoginCLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuarioC1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(pf_contraC1)))
                    .addGroup(jd_LoginCLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_LoginCLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jb_GuardarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jd_LoginCLayout.setVerticalGroup(
            jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuarioC1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_LoginCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_contraC1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_GuardarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Spotify");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 255, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Usuario");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 255, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Contrasenia");

        tf_usuarioA1.setBackground(new java.awt.Color(0, 0, 0));
        tf_usuarioA1.setForeground(new java.awt.Color(102, 255, 51));

        pf_contraA1.setBackground(new java.awt.Color(0, 0, 0));
        pf_contraA1.setForeground(new java.awt.Color(102, 255, 0));

        jb_GuardarA1.setBackground(new java.awt.Color(0, 0, 0));
        jb_GuardarA1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_GuardarA1.setForeground(new java.awt.Color(102, 255, 51));
        jb_GuardarA1.setText("LOGIN");
        jb_GuardarA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarA1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginALayout = new javax.swing.GroupLayout(jd_LoginA.getContentPane());
        jd_LoginA.getContentPane().setLayout(jd_LoginALayout);
        jd_LoginALayout.setHorizontalGroup(
            jd_LoginALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_LoginALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(jd_LoginALayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jd_LoginALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LoginALayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(pf_contraA1))
                    .addGroup(jd_LoginALayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(tf_usuarioA1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addGap(170, 170, 170))
            .addGroup(jd_LoginALayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jb_GuardarA1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_LoginALayout.setVerticalGroup(
            jd_LoginALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jd_LoginALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuarioA1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_LoginALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_contraA1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_GuardarA1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jf_ArtistasLayout = new javax.swing.GroupLayout(jf_Artistas.getContentPane());
        jf_Artistas.getContentPane().setLayout(jf_ArtistasLayout);
        jf_ArtistasLayout.setHorizontalGroup(
            jf_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        jf_ArtistasLayout.setVerticalGroup(
            jf_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        ta_1.setColumns(20);
        ta_1.setRows(5);
        jScrollPane1.setViewportView(ta_1);

        jMenu1.setText("CRUD");

        jm_ListarU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jm_ListarU.setText("ListarUsuario");
        jm_ListarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ListarUActionPerformed(evt);
            }
        });
        jMenu1.add(jm_ListarU);

        jm_ModificarU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jm_ModificarU.setText("ModificarUsuario");
        jm_ModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ModificarUActionPerformed(evt);
            }
        });
        jMenu1.add(jm_ModificarU);

        jm_DeleteU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jm_DeleteU.setText("DeleteUsuario");
        jm_DeleteU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_DeleteUActionPerformed(evt);
            }
        });
        jMenu1.add(jm_DeleteU);

        jm_ListarA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_ListarA.setText("ListarArtista");
        jMenu1.add(jm_ListarA);

        jm_ModificarA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_ModificarA.setText("ModificarArtista");
        jMenu1.add(jm_ModificarA);

        jm_DeleteA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_DeleteA.setText("DeleteArtista");
        jm_DeleteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_DeleteAActionPerformed(evt);
            }
        });
        jMenu1.add(jm_DeleteA);

        menuBar.add(jMenu1);

        CRUD.setJMenuBar(menuBar);

        javax.swing.GroupLayout CRUDLayout = new javax.swing.GroupLayout(CRUD.getContentPane());
        CRUD.getContentPane().setLayout(CRUDLayout);
        CRUDLayout.setHorizontalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        CRUDLayout.setVerticalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jb_spotify.setBackground(new java.awt.Color(0, 0, 0));
        jb_spotify.setFont(new java.awt.Font("Swis721 Hv BT", 1, 60)); // NOI18N
        jb_spotify.setForeground(new java.awt.Color(51, 255, 0));
        jb_spotify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jb_spotify.setText("Spotify");

        jb_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7p2_gerardodiaz/Spotify.png"))); // NOI18N
        jb_pic.setText("jLabel2");

        jb_Sign.setBackground(new java.awt.Color(0, 0, 0));
        jb_Sign.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_Sign.setForeground(new java.awt.Color(102, 255, 51));
        jb_Sign.setText("Sign Up");
        jb_Sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SignMouseClicked(evt);
            }
        });
        jb_Sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SignActionPerformed(evt);
            }
        });

        jb_Login.setBackground(new java.awt.Color(0, 0, 0));
        jb_Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_Login.setForeground(new java.awt.Color(102, 255, 0));
        jb_Login.setText("Login");
        jb_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LoginMouseClicked(evt);
            }
        });
        jb_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LoginActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(102, 255, 51));
        jToggleButton1.setText("CRUD");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_spotify, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Sign, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jb_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_pic)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jb_spotify, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Sign, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_SignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_SignActionPerformed

    private void jb_SignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SignMouseClicked
        // TODO add your handling code here:
        jf_Sign.setLocationRelativeTo(this);
        jf_Sign.pack();
        jf_Sign.setVisible(true);
    }//GEN-LAST:event_jb_SignMouseClicked

    private void jb_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ClienteMouseClicked
        // TODO add your handling code here:
        jd_signC.setModal(true);
        jd_signC.pack();
        jd_signC.setLocationRelativeTo(this);
        jd_signC.setVisible(true);
        
        jf_Sign.dispose();
        
    }//GEN-LAST:event_jb_ClienteMouseClicked

    private void jb_GuardarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarCMouseClicked
        // TODO add your handling code here:
        Clientes cl = new Clientes();
        administrarUsuarios ap
                = new administrarUsuarios("./UsuariosC.txt");
        ap.cargarArchivo();
        String usu, contra, method;
        int edad;
        
        usu = tf_usuarioC.getText();
        cl.setUsermane(usu);
        contra = pf_contraC.getText();
        cl.setContrasenia(contra);
        method = tt_edadC.getText();
        edad = Integer.parseInt(method);
        cl.setEdad(edad);
        
        
        Clientes c = new Clientes(usu, contra, edad);
        UsuarioC.add(c);
        
        
        ap.getListaUsuarios().add(c);
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         JOptionPane.showMessageDialog(this,
                "Se guardaron los datos");
        tf_usuarioC.setText("");
        pf_contraC.setText("");
        tt_edadC.setText("");
        jd_signC.dispose();;
        
        
                    
        
    }//GEN-LAST:event_jb_GuardarCMouseClicked

    private void jb_ArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ArtistaMouseClicked
        // TODO add your handling code here:
        jd_signA.setModal(true);
        jd_signA.pack();
        jd_signA.setLocationRelativeTo(this);
        jd_signA.setVisible(true);
        
        jf_Sign.dispose();
    }//GEN-LAST:event_jb_ArtistaMouseClicked

    private void tf_usuarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuarioAActionPerformed

    private void jb_GuardarAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarAMouseClicked
        // TODO add your handling code here:
        Artistas ar = new Artistas();
        administrarUsuarios ap
                = new administrarUsuarios("./UsuariosA.txt");
        ap.cargarArchivo();
        String usu, contra, method, nombre;
        int edad;
        
        usu = tf_usuarioA.getText();
        ar.setUsermane(usu);
        contra = pf_contraA.getText();
        ar.setContrasenia(contra);
        method = tt_edadA.getText();
        edad = Integer.parseInt(method);
        ar.setEdad(edad);
        nombre = tf_nombreA.getText();
        ar.setNombre(nombre);
        
        
        Artistas a = new Artistas(nombre, usu, contra, edad);
        UsuarioA.add(a);
        ap.getListaUsuarios().add(a);
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         JOptionPane.showMessageDialog(this,
                "Se guardaron los datos");
        tf_usuarioA.setText("");
        pf_contraA.setText("");
        tt_edadA.setText("");
        tf_nombreA.setText("");
        jd_signA.dispose();
        
    }//GEN-LAST:event_jb_GuardarAMouseClicked

    private void tf_nombreAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreAActionPerformed

    private void jb_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_LoginActionPerformed

    private void jb_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LoginMouseClicked
        // TODO add your handling code here:
        jf_Login.setLocationRelativeTo(this);
        jf_Login.pack();
        jf_Login.setVisible(true);
        
    }//GEN-LAST:event_jb_LoginMouseClicked

    private void jb_Cliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Cliente1MouseClicked
        // TODO add your handling code here:
        jd_LoginC.setModal(true);
        jd_LoginC.pack();
        jd_LoginC.setLocationRelativeTo(this);
        jd_LoginC.setVisible(true);
        
        jf_Login.dispose();
        
    }//GEN-LAST:event_jb_Cliente1MouseClicked

    private void jb_Artista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Artista1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jb_Artista1MouseClicked

    private void jb_GuardarC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarC1MouseClicked
        // TODO add your handling code here:
        
        String usuario, contra;
        usuario= tf_usuarioC1.getText();
        contra = pf_contraC1.getText();
        for (int i = 0; i < UsuarioC.size(); i++) {
            
            
            
            if (usuario.equals((UsuarioC.get(i).getUsermane())) && contra.equals(UsuarioC.get(i).getContrasenia()))  {
                JOptionPane.showMessageDialog(this,
                        "ENTRO"); 
                
                jd_login.dispose();
               

            } else {
                JOptionPane.showMessageDialog(this,
                        "Se equivoco de Datos");
                tf_usuarioC1.setText("");
                pf_contraC1.setText("");
                jd_login.dispose();
            }
        
        }
    }//GEN-LAST:event_jb_GuardarC1MouseClicked

    private void jb_GuardarA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarA1MouseClicked
        // TODO add your handling code here:
        String usuario, contra;
        usuario= tf_usuarioA1.getText();
        contra = pf_contraA1.getText();
        for (int i = 0; i < UsuarioC.size(); i++) {
            
            
            
            if (usuario.equals((UsuarioA.get(i).getUsermane())) && contra.equals(UsuarioA.get(i).getContrasenia()))  {
                JOptionPane.showMessageDialog(this,
                        "ENTRO"); 
                
                jd_login.dispose();
               

            } else {
                JOptionPane.showMessageDialog(this,
                        "Se equivoco de Datos");
                tf_usuarioA1.setText("");
                pf_contraA1.setText("");
                jd_login.dispose();
            }
        
        }
        
    }//GEN-LAST:event_jb_GuardarA1MouseClicked

    private void jm_ListarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ListarUActionPerformed
        // TODO add your handling code here:
        ta_1.setText("");
        administrarUsuarios ap
                = new administrarUsuarios("./UsuariosC.txt");
        ap.cargarArchivo();
        
        for (Usuarios t : ap.getListaUsuarios()) {
           ta_1.append(ap.getListaUsuarios().indexOf(t) + "- " + t.toString());
           
           
        }
        
    }//GEN-LAST:event_jm_ListarUActionPerformed

    private void jm_DeleteUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_DeleteUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_DeleteUActionPerformed

    private void jm_DeleteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_DeleteAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_DeleteAActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        CRUD.setLocationRelativeTo(this);
        CRUD.pack();
        CRUD.setVisible(true);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jm_ModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ModificarUActionPerformed
        // TODO add your handling code here:
        administrarUsuarios ap
                = new administrarUsuarios("./UsuariosC.txt");
        int p;
        String u,c;
        int e;
        p = Integer.parseInt(JOptionPane.showInputDialog("Posicion"));
        u = JOptionPane.showInputDialog("Nuevo Usuario");
        c = JOptionPane.showInputDialog("Nueva Contrasenia");
        e = Integer.parseInt(JOptionPane.showInputDialog("Nueva Edad"));
        
        

        ap.cargarArchivo();
        ap.getListaUsuarios().get(p).setUsermane(u);
        ap.getListaUsuarios().get(p).setContrasenia(c);
        ap.getListaUsuarios().get(p).setEdad(e);
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jm_ModificarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CRUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jb_Artista;
    private javax.swing.JButton jb_Artista1;
    private javax.swing.JButton jb_Cliente;
    private javax.swing.JButton jb_Cliente1;
    private javax.swing.JButton jb_GuardarA;
    private javax.swing.JButton jb_GuardarA1;
    private javax.swing.JButton jb_GuardarC;
    private javax.swing.JButton jb_GuardarC1;
    private javax.swing.JButton jb_Login;
    private javax.swing.JButton jb_Sign;
    private javax.swing.JLabel jb_pic;
    private javax.swing.JLabel jb_spotify;
    private javax.swing.JLabel jb_spotify1;
    private javax.swing.JDialog jd_LoginA;
    private javax.swing.JDialog jd_LoginC;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_signA;
    private javax.swing.JDialog jd_signC;
    private javax.swing.JFrame jf_Artistas;
    private javax.swing.JFrame jf_Login;
    private javax.swing.JFrame jf_Sign;
    private javax.swing.JMenuItem jm_DeleteA;
    private javax.swing.JMenuItem jm_DeleteU;
    private javax.swing.JMenuItem jm_ListarA;
    private javax.swing.JMenuItem jm_ListarU;
    private javax.swing.JMenuItem jm_ModificarA;
    private javax.swing.JMenuItem jm_ModificarU;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPasswordField pf_contraA;
    private javax.swing.JPasswordField pf_contraA1;
    private javax.swing.JPasswordField pf_contraC;
    private javax.swing.JPasswordField pf_contraC1;
    private javax.swing.JTextArea ta_1;
    private javax.swing.JTextField tf_nombreA;
    private javax.swing.JTextField tf_usuarioA;
    private javax.swing.JTextField tf_usuarioA1;
    private javax.swing.JTextField tf_usuarioC;
    private javax.swing.JTextField tf_usuarioC1;
    private javax.swing.JTextField tt_edadA;
    private javax.swing.JTextField tt_edadC;
    // End of variables declaration//GEN-END:variables
    
    ArrayList<Usuarios> UsuarioC = new ArrayList();
    ArrayList<Usuarios> UsuarioA = new ArrayList();
}
